version: '3.5'
services:
  postgres:
    image: postgres:9.5-alpine
    container_name: "postgres"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - 5432:5432
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - postgres
